### ISSUE TITLE
Some questions : disk space, performance for dense matrix, etc.

### ISSUE THREAD

**Issue by gocanal** [jfkelley/hadoop-matrix-mult#1]
Hello,
First of all, thank you very much for sharing the code. I have successfully run the program on a single node cluster for 1k x 1k square matrix multiplication. I have a couple of questions:
1. how efficient is this algorithm for dense matrix ?
   I was trying to run a 16384 x 16384 dense matrix multiplication but run into 'disk space full' after 3 hours on a single node cluster (64-bit Ubuntu 14.04, 4GB RAM, 4-core Intel i3-3240 @ 3.40 Ghz). One matrix file size is 8GB. It used 100GB over after three hours I think (until running of space). So this leads to my second question:
2. is it possible to calculate roughly the space needed, given matrix size and nDivs ?
3. In CompressedMatrixMultiply, we have set chunkSize to 1024 \* 128, does it mean that this is the biggest sub matrix we can support (i.e. roughly 360 x 360) for dense matrix ?

thank you very much

**Comment by jfkelley** [comment]
Hi gocanal,

First, I apologize for this being such a late reply. I did not realize that I had notifications for issues turned off.
1. This is not very efficient for dense matrixes. It is not asymptotically (big-O) slower than a better algorithm, but in practice it will probably be much slower than some other approach. It is very optimized for sparse matrixes. My understanding is that GPU-based approaches are the current best practice for a large dense matrix.
2. What did you have nDivs set to? The disk space usage is approximately the input data volume times nDivs.
3. The chunk size in CompressedMatrixMultiply is not really relevant. Basically, the code used to not output in chunks and just added directly to an ArrayList<Integer>. However, appending to an arraylist has some overhead, so to further optimize, I fill up a "chunk" in an int[], then eventually add that int[] to an ArrayList<int[]>. 1024*128 is pretty arbitrary and has no real bearing on execution size limits.
